# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics
        uses: T-Pakorn
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugin_isocalendar: yes
          config_timezone: Europe/Paris
          config_order: base.header, isocalendar, base.repositories
          config_padding: 10%
          
          
          
          
        

          # Options
          user: T-Pakorn
          template: classic
          base: ""
          config_animated: yes
          config_timezone: Asia/Bangkok
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          
          
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: playlist
          plugin_music_playlist: https://open.spotify.com/embed/playlist/7wdYqwFU3YuunizA5hwDwj # Extracted source link
          plugin_music_limit: 4
          plugins_errors_fatal: yes
